spring.application.name=ServizioRapido

# Configurazione Database

spring.datasource.url=jdbc:postgresql://localhost:5432/ServizioRapido
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=webproject.unical@gmail.com
spring.mail.password=uuzf oans afjg rnzf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true